### ISSUE TITLE
The documentation is bad.

### ISSUE THREAD

**Issue by supermoos** [epiloque/element-dataset#1]
You're suppose to call elementDatasetPolyfill() - but that function is non exsistent in the polyfill minified download?

**Comment by epiloque** [comment]
You need an amd load such as dojo.js or require.js. The loader defines functions for interacting with it - require and define.

Alternatively element-dataset is available as a commonjs module.

**Comment by rhys-vdw** [comment]
A usage example in the README would be great for this one. I was stumped for a while just importing it (as one would babel-polyfilly). But now it's working like a charm, thanks!
