### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by tremby** [epiloque/element-dataset#10]
Please add usage instructions to the readme. Both times I've used this polyfill I've had to read the source code to figure out what I'm meant to do to have it run.

**Comment by tremby** [comment]
For posterity, with webpack it was `require('element-dataset')()`, but with browserify I needed `require('element-dataset').default()`.

**Comment by tremby** [comment]
So were you going to add something to the readme, or not...? Something along the lines of "this module exports a function. Call this function to set up the polyfill."

**Comment by gmhenderson** [comment]
I had the same trouble. In my case I'm using Webpack (with vue-loader) and had to do `require('element-dataset).default()`

**Comment by tremby** [comment]
@epiloque: you've now had three tickets (#1, #8, and this one) asking you to add something to the readme. Why not do it?

**Comment by epiloque** [comment]
Upgrading the bundle and testing dependencies. Will circle back to this after that & probably add a clean module exports to the commonjs bundle.

**Comment by samburgers** [comment]
@gmhenderson theres a missing `singlequote` in your example, but when fixed that works. thanks
