### ISSUE TITLE
BUG: jsnext:main is not transpilled

### ISSUE THREAD

**Issue by tinovyatkin** [epiloque/element-dataset#3]
As per specification https://github.com/rollup/rollup/wiki/jsnext:main everything less `import` and `export` must be transpilled in `jsnext:main` pointed version, but your still have `let` declaration in the loop that is not exactly supported by target browser.

As result it will not bundle correctly with Rollup, leaving `let` inside.

**Comment by epiloque** [comment]
Thank you for the report! Messed up the build step with the latest update.
