### ISSUE TITLE
element-dataset depends on babel-runtime

### ISSUE THREAD

**Issue by Kovensky** [epiloque/element-dataset#5]
Avoid using transform-runtime on libraries, especially when they are intended to run on browsers; this requires that users bundle `babel-runtime`, which will end up bundling a *second* copy of `core-js` (a regular copy + a library mode copy) should the user also use `babel-polyfill`.

You could require that users provide a polyfill for `Object.defineProperty` and `Object.getOwnPropertyDescriptor`; however, this polyfill would not work anyway without native support for them. The only reason they are getting replaced by transform-runtime is to add `Symbol` support, which is not used by this polyfill.

---

PS: If you change `const map = {}` to `const map = Object.create(null)`, `core-js` _might_ be able to make an object that can have `Object.defineProperty` called on it on IE8. Note that I never tested this.

**Comment by epiloque** [comment]
I think this is relevant https://github.com/babel/babel/issues/965
